from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NUM_CLASSES = 8
_C.MODEL.NUM_HEADS = 12

_C.INPUT = CN()
_C.INPUT.IMAGE_SIZE = 224
_C.DATASET = CN()

_C.DATALOADER = CN()

_C.SOLVER = CN()
_C.SOLVER.BASE_LR= 0.01
_C.SOLVER.WEIGHT_DECAY= 0.0001
_C.SOLVER.IMS_PER_BATCH= 4
_C.SOLVER.OPTIMIZER_NAME = "Adam"
_C.SOLVER.WEIGHT_DECAY_BIAS = 0.3

_C.OUTPUT_DIR = ""

_C.TEST = CN()
_C.TEST.IMS_PER_BATCH = 2

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 2

